=== MrLucasFischer/Java-ORM/out/production/DBMLab/metamodels/model.dtd
<!ELEMENT model (class+, foreignKey*)>
<!ATTLIST model
    name CDATA #REQUIRED>

<!ELEMENT class (attribute+)>
    <!ATTLIST class
    name CDATA #REQUIRED>

<!ELEMENT attribute EMPTY>
    <!ATTLIST attribute
    name CDATA #REQUIRED
    type CDATA #REQUIRED
    required CDATA "false"> <!--  by default this attribute is false -->

<!ELEMENT foreignKey EMPTY>
    <!ATTLIST foreignKey
    type CDATA #REQUIRED
    firstClass CDATA #REQUIRED
    secondClass CDATA #REQUIRED
    firstClassRequired CDATA "true"
    secondClassRequired CDATA "false">

=== MrLucasFischer/Java-ORM/out/production/DBMLab/models/bookstore.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE model SYSTEM "../metamodels/model.dtd">
<model name="Bookstore">
    <class name="Author">
        <attribute name="first_name" type="String" />
        <attribute name="last_name" type="String" />
        <attribute name="email" type="String" />
        <foreignKey name="Book" type="121"/> <!-- Seria como estar a dizer "Um autor pode ter um livro" -->
    </class>
    <class name="Book">
        <attribute name="title" type="String" />
        <attribute name="pubDate" type="Date" />
        <attribute name="price" type="double" />
        <attribute name="quantity" type="int" />
        <foreignKey name="Author" type="12N"/> <!-- Seria como estar a dizer "Um livro tem um ou mais autores" -->
    </class>

</model>
